---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: gitlab
  namespace: gitlab
spec:
  parentRefs:
  - name: private-gateway
    namespace: infra
  hostnames:
  - "{{ .Values.global.gitlab_url }}"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /admin/sidekiq
    backendRefs:
    - kind: Service
      name: gitlab-webservice-default
      port: 8080
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - kind: Service
      name: gitlab-webservice-default
      port: 8181
