instances: 3
superuser_secret: superuser-secret
db_user_secret: sentry-skymng-db-user-secret
db_user_name: sentry-skymng
db_name: sentry-db
cluster_name: sentry

storage:
  storage_class: local-ssd
  storage_size: 40Gi
  wal_storage_size: 4Gi

image:
  imageName: repo.rovzane.com/ghcr/cloudnative-pg/postgresql
  tag: 16.1

s3:
  destinationPath: s3://skyroom-sentry/sentry-pg 
  endpointURL: https://s3.ir-thr-at1.arvanstorage.ir
  secretName:  sentry-pd-s3-backup
  accessKeyId: ACCESS_KEY
  secretAccessKey: SECRET_KEY
