replicas: 3

storage:
  storage_class: local-ssd
  storage_size: 40Gi

postgres_version: 15
image:
  imageName: repo.rovzane.com/crunchydata/crunchydata/crunchy-postgres
  tag: ubi8-15.3-2

backups:
  image: repo.rovzane.com/crunchydata/crunchydata/crunchy-pgbackrest
  tag: ubi8-2.45-2
  s3:
    bucket: "sentry-backup"
    region: "simin"
    endpoint: https://s3.ir-thr-at1.arvanstorage.ir
  storage:
    storage_class: local-hdd
    storage_size: 40Gi