apiVersion: v2
name: keycloak
description: An umbrella chart for keycloak
type: application
version: 0.1.0
dependencies:
  - name: keycloak
    version: 19.x.x
    repository: "https://repo.rovzane.com/artifactory/bitnami-charts/"
  - name: postgresql
    version: 14.x.x
    repository: "https://repo.rovzane.com/artifactory/bitnami-charts/"
    condition: postgresql.enabled