pg_db:
  replicas: 3

  storage:
    storage_class: local-ssd
    storage_size: 40Gi

  postgres_version: 15
  image:
    imageName: repo.rovzane.com/crunchydata/crunchydata/crunchy-postgres
    tag: ubi8-15.3-2

  backups:
    image: repo.rovzane.com/crunchydata/crunchydata/crunchy-pgbackrest
    tag: ubi8-2.45-2
    s3:
      bucket: "sentry-backup"
      region: "simin"
      endpoint: https://s3.ir-thr-at1.arvanstorage.ir
    storage:
      storage_class: local-hdd
      storage_size: 40Gi

sentry:
  clickhouse:
    clickhouse:
      image: repo.rovzane.com/dockerhub/yandex/clickhouse-server
    tabix:
      image: repo.rovzane.com/dockerhub/spoonest/clickhouse-tabix-web-client
  zookeeper:
    image:
      registry: "repo.rovzane.com"
      repository: dockerhub/bitnami/zookeeper
  rabbitmq:
    image:
      registry: "repo.rovzane.com"
      repository: dockerhub/bitnami/rabbitmq
  kafka:
    zookeeper:
      image:
        registry: "repo.rovzane.com"
        repository: dockerhub/bitnami/zookeeper
    image:
      registry: "repo.rovzane.com"
      repository: dockerhub/bitnami/kafka
  redis:
    image:
      registry: "repo.rovzane.com"
      repository: dockerhub/bitnami/redis
  memcached:
    image:
      registry: "repo.rovzane.com"
      repository: dockerhub/bitnami/memcached
  user:
    create: true
    email: m.barazandeh110@gmail.com
    password: 89WPXq7u7vif
  images:
    snuba:
      repository: repo.rovzane.com/dockerhub/getsentry/snuba
    sentry:
      repository: repo.rovzane.com/dockerhub/getsentry/sentry
    relay:
      repository: repo.rovzane.com/dockerhub/getsentry/relay
  ingress:
    enabled: false
    regexPathStyle: nginx
    hostname: sentry.rovzane.com
  sentry:
    singleOrganization: false
    cron:
      logLevel: WARNING
    worker:
      replicas: 3
  service:
    name: sentry
    type: ClusterIP
    annotations: {}
  postgresql:
    enabled: false
  externalPostgresql:
    host: sentry-db-primary
    port: 5432
    username: sentry-skymng
    password: "LJEyUndXV241GMn2LJCo"
    database: sentry
  # nginx:
  #   enabled: false
  system:
    url: "http://sentry.rovzane.com"
    public: false
  hooks:
    enabled: true
    removeOnSuccess: true
    activeDeadlineSeconds: 1500
