gitlab:
  artifact_s3_storage: gitlab-artifacts-s3
  s3_storage: backup-s3
  root_password: gitlab-root-password
  cache_s3_storage: gitlab-runner-cache-s3
  sso: gitlab-sso

gitlab_runner:
  cache_secret: gitlab-runner-cache-secret
