---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: elastic-apm
  namespace: elastic
spec:
  parentRefs:
  - name: public-gateway
    namespace: infra
  hostnames:
  - "apm.rovzane.com"
  - "apm2.rovzane.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
      method: GET
    - path:
        type: PathPrefix
        value: /
      method: OPTIONS
    - path:
        type: PathPrefix
        value: /
      method: POST
    filters:
    - type: ResponseHeaderModifier
      responseHeaderModifier:
        remove:
          - "Access-Control-Allow-Origin"
        add:
          - name: "Access-Control-Allow-Origin"
            value: "*"
          - name: "Access-Control-Allow-Headers"
            value: "authorization"
    backendRefs:
    - kind: Service
      name: apmserver-apm-http
      port: 8200
