apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apmserver
spec:
  version: {{ .Values.version }}
  count: 3
  elasticsearchRef:
    name: {{ .Values.clustername }}
  kibanaRef:
    name: kibana
