---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: private-gateway
  namespace: infra
  annotations:
    "io.cilium/lb-ipam-ips": "172.16.133.128"
    metallb.universe.tf/loadBalancerIPs: "172.16.133.128"
spec:
  gatewayClassName: private
  addresses:
  - type: IPAddress
    value: 172.16.133.128
  listeners:
  - name: private-rovzane-https
    protocol: HTTPS
    port: 443
    allowedRoutes:
      namespaces:
        from: Selector
        selector:
          matchLabels:
            private-gateway-access: "true"
    hostname: "*.rovzane.com"
    tls:
      certificateRefs:
      - kind: Secret
        name: tls-rovzane
