apiVersion: v1
data:
  accesskey: NjZhNWE1ZmEtMTY4Zi00MmM1LTk1YjgtYjdhNDgxNDQ2MDBl
  secretkey: N2EyMjFmN2IyZWViN2RmN2VkODk3NTcyZjJmNzkyZmI3ZWFmMmQyMzZiNzBjMjYyNThjMjA1YWI0NTU0NDRjMw==
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Values.gitlab_runner.cache_secret }}
  namespace: gitlab
