apiVersion: v1
data:
  connection: cHJvdmlkZXI6IEFXUwpyZWdpb246IFNpbWluCmF3c19hY2Nlc3Nfa2V5X2lkOiA2NmE1YTVmYS0xNjhmLTQyYzUtOTViOC1iN2E0ODE0NDYwMGUKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5OiA3YTIyMWY3YjJlZWI3ZGY3ZWQ4OTc1NzJmMmY3OTJmYjdlYWYyZDIzNmI3MGMyNjI1OGMyMDVhYjQ1NTQ0NGMzCmhvc3Q6IHNreXJvb20tZ2l0LnMzLmlyLXRoci1hdDEuYXJ2YW5zdG9yYWdlLmlyCmF3c19zaWduYXR1cmVfdmVyc2lvbjogNAplbmRwb2ludDogaHR0cHM6Ly9za3lyb29tLWdpdC5zMy5pci10aHItYXQxLmFydmFuc3RvcmFnZS5pcgpwYXRoX3N0eWxlOiB0cnVlCg==
kind: Secret
metadata:
  name: {{ .Values.gitlab.artifact_s3_storage }}
  namespace: gitlab
type: Opaque
