image:
  repository: repo.rovzane.com/dockerhub/velero/velero

upgradeCRDs: true

credentials:
  useSecret: true
  existingSecret: velero-arvan-secret

configuration:
  backupStorageLocation:
    - name: "velero"
      provider: aws
      bucket: backup-tools
      prefix: velero-tools
      config:
        region: simin
        s3ForcePathStyle: true
        publicUrl: https://s3.ir-thr-at1.arvanstorage.ir
        s3Url: https://s3.ir-thr-at1.arvanstorage.ir

snapshotsEnabled: false

schedules:
  #  clustertestbackuo:
  #    schedule: "0 */5 * * *"
  #    template:
  #      snapshotVolumes: false      
  #      ttl: "168h"
  #      includedNamespaces:
  #       - '*'

    gitlabbackuo:
      schedule: "every 6h"
      template:
        snapshotVolumes: false      
        ttl: "168h"
        includedNamespaces:
        - 'gitlab'

initContainers: 
    - name: velero-plugin-for-csi
      image: velero/velero-plugin-for-csi:v0.7.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.9.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins