instances: 3

superuser_secret: superuser-secret
db_user_secret: gitlab-skymng-db-user-secret
db_user_name: gitlab-skymng
db_name: gitlab-db
cluster_name: gitlab

storage:
  storage_class: local-ssd
  storage_size: 40Gi
  wal_storage_size: 4Gi

image:
  imageName: repo.rovzane.com/ghcr/cloudnative-pg/postgresql
  tag: 16.1

s3:
  destinationPath: s3://skyroom-git/gitlab-pg 
  endpointURL: https://s3.ir-thr-at1.arvanstorage.ir
  secretName:  gitlab-pd-s3-backup
  accessKeyId: ACCESS_KEY
  secretAccessKey: SECRET_KEY